apiVersion: apps/v1
Kind: Deployment
metadata:
     name: redis
 lables:
      app: redis
 spec:
   replicas: 1 
selector:
        matchlables:
              app: redis
       templete:
           metadata:
             lables:
                 app: redis
       spec:
               containers:
                       -name: redis-app
                       image: redis:latest 
                       ports:
                         -containerport: 6379
---
apiVersion: v1
kind: service
metadata: 
name: redis-service
lables: 
app: redis
spec:
   selector:
         app: redis
         type: NodePort
         ports:
             -nodeport: 3111
             port: 8080
             targetport: 8080


